baseURL = 'https://aroaming.github.io'
publishDir = 'docs'
theme = 'paper'
author = "Aroaming"
copyright = "Copyright © 2022; all rights reserved."
paginate = 8
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
timeout = 30000
title = '装笔笔记'

[params]
    # show header social icons
    twitter = 'aroaming2'     # twitter.com/YOUR_TWITTER_ID
    #github = 'YOUR_GITHUB_ID'       # github.com/YOUR_GITHUB_ID
    #instagram = 'YOUR_INSTAGRAM_ID' # instagram.com/YOUR_INSTAGRAM_ID
    rss = true                      # show rss icon with link

    #show home page profile
    #avatar = 'https://s3.bmp.ovh/imgs/2022/07/20/2768fe7c65c3dc51.jpg' 
    #name = '装笔笔记'
    #bio = 'aroaming'

    # misc
    disableHLJS = true              # disable requesting highlight.js
    monoDarkIcon = true             # show monochrome dark mode icon


[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[privacy]

  [privacy.vimeo]
    disabled = false
    simple = true

  [privacy.twitter]
    disabled = false
    enableDNT = true
    simple = true
    disableInlineCSS = true

  [privacy.instagram]
    disabled = false
    simple = true

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true